Add timeout option to the wait-for-deployment script (#4)

diff --git a/wait-for-deployment b/wait-for-deployment
--- a/wait-for-deployment
+++ b/wait-for-deployment
@@ -12,7 +12,14 @@ set -o errexit
 set -o pipefail
 set -o nounset
 
-deployment=
+DEFAULT_TIMEOUT=60
+
+monitor_timeout() {
+  local -r wait_pid="$1"
+  sleep "${timeout}"
+  echo "Timeout ${timeout} exceeded" >&2
+  kill "${wait_pid}"
+}
 
 get_generation() {
   get_deployment_jsonpath '{.metadata.generation}'
@@ -36,28 +43,50 @@ get_deployment_jsonpath() {
   kubectl get deployment "${deployment}" -o "jsonpath=${jsonpath}"
 }
 
-if [[ $# != 1 ]]; then
-  echo "usage: $(basename "$0") <deployment>" >&2
+display_usage_and_exit() {
+  echo "Usage: $(basename "$0") <deployment> <[timeout]>" >&2
+  echo "Arguments:" >&2
+  echo "deployment - REQUIRED: The name of the deployment the script should wait on" >&2
+  echo "timeout    - OPTIONAL: How long to wait for the deployment to be available, defaults to ${DEFAULT_TIMEOUT} seconds, must be greater than 0" >&2
   exit 1
+}
+
+if [ $# -lt 1 ] || [ $# -gt 2 ] ; then
+  display_usage_and_exit
 fi
 
 readonly deployment="$1"
 
-generation=$(get_generation); readonly generation
-echo "waiting for specified generation ${generation} to be observed"
-while [[ $(get_observed_generation) -lt ${generation} ]]; do
+declare -xr timeout=${2:-$DEFAULT_TIMEOUT}
+if [[ ${timeout} -le 0 ]]; then
+  display_usage_and_exit
+fi
+
+echo "Waiting for deployment with timeout ${timeout} seconds"
+
+monitor_timeout $$ &
+readonly timeout_monitor_pid=$!
+
+trap 'kill ${timeout_monitor_pid}' EXIT #Stop timeout monitor
+
+generation=$(get_generation);  readonly generation
+current_generation=$(get_observed_generation)
+
+echo "Expected generation for deployment ${deployment}: ${generation}"
+while [[ ${current_generation} -lt ${generation} ]]; do
   sleep .5
+  echo "Currently observed generation: ${current_generation}"
 done
-echo "specified generation observed."
+echo "Observed expected generation: ${current_generation}"
 
 replicas="$(get_replicas)"; readonly replicas
-echo "specified replicas: ${replicas}"
+echo "Expected replicas: ${replicas}"
 
-available=-1
-while [[ ${available} -ne ${replicas} ]]; do
+available=$(get_available_replicas)
+while [[ ${available} -lt ${replicas} ]]; do
   sleep .5
+  echo "Available replicas: ${available}, waiting"
   available=$(get_available_replicas)
-  echo "available replicas: ${available}"
 done
 
-echo "deployment complete."
+echo "Deployment of service ${deployment} successful. All ${available} replicas ready"
