refactored back to only one commandline parameter including type and resource name

diff --git a/wait-for-deployment b/wait-for-deployment
--- a/wait-for-deployment
+++ b/wait-for-deployment
@@ -52,14 +52,13 @@ get_ready_replicas() {
 get_deployment_jsonpath() {
   local -r jsonpath="$1"
 
-  kubectl --namespace "${namespace}" get "${type}" "${deployment}" -o "jsonpath=${jsonpath}"
+  kubectl --namespace "${namespace}" get "${deployment}" -o "jsonpath=${jsonpath}"
 }
 
 display_usage_and_exit() {
-  echo "Usage: $(basename "$0") [-n <namespace>] [-t <timeout>] <deployment|statefulset> <resource-name>" >&2
+  echo "Usage: $(basename "$0") [-n <namespace>] [-t <timeout>] [deployment|statefulset]/<resource-name>" >&2
   echo "Arguments:" >&2
-  echo "deployment|statefulset REQUIRED: the type of kubernetes resource to be waited for: deployment or statefulset, other types are not supported" >&2
-  echo "resource-name REQUIRED: The name of the deployment the script should wait on" >&2
+  echo "[deployment/statefulset]/resource-name REQUIRED: The type and name of the resource the script should wait on. Currently the supported types are deployment and statefulset are supported." >&2
   echo "-n OPTIONAL: The namespace the deployment exists in, defaults is the 'default' namespace" >&2
   echo "-t OPTIONAL: How long to wait for the deployment to be available, defaults to ${DEFAULT_TIMEOUT} seconds, must be greater than 0" >&2
   exit 1
@@ -78,17 +77,25 @@ do
 done
 
 shift $((OPTIND-1))
-if [ "$#" -ne 2 ] ; then
+if [ "$#" -ne 1 ] ; then
   display_usage_and_exit
 fi
-readonly type="$1"
-readonly deployment="$2"
+deployment="$1"
 
 if [[ ${timeout} -le 0 ]]; then
   display_usage_and_exit
 fi
 
-echo "Waiting for ${type} ${deployment} in namespace ${namespace} with a timeout ${timeout} seconds"
+# add deployment as type if no type specified (backwards compatibility)
+if ! [[ $deployment =~ .*/.* ]]; then
+  deployment="deployment/$deployment"
+fi
+
+if [[ ! $deployment =~ deployment/.* ]] && [[ ! $deployment =~ statefulset/.* ]]; then
+  display_usage_and_exit
+fi
+
+echo "Waiting for ${deployment} in namespace ${namespace} with a timeout ${timeout} seconds"
 
 monitor_timeout $$ &
 readonly timeout_monitor_pid=$!
@@ -98,7 +105,7 @@ trap 'kill -- -${timeout_monitor_pid}' EXIT #Stop timeout monitor
 generation=$(get_generation);  readonly generation
 current_generation=$(get_observed_generation)
 
-echo "Expected generation for ${type} ${deployment}: ${generation}"
+echo "Expected generation for ${deployment}: ${generation}"
 while [[ ${current_generation} -lt ${generation} ]]; do
   sleep .5
   echo "Currently observed generation: ${current_generation}"
@@ -121,4 +128,4 @@ while [[ ${updated_replicas} -lt ${specified_replicas} || ${current_replicas} -g
   ready_replicas=$(get_ready_replicas)
 done
 
-echo "Deployment/update of ${type} ${deployment} successful. All ${ready_replicas} replicas are ready."
+echo "Update of ${deployment} successful. All ${ready_replicas} replicas are ready."
